// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fuotaDeployment.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FUOTADeploymentState int32

const (
	// Create multicast-group.
	FUOTADeploymentState_MULTICAST_CREATE FUOTADeploymentState = 0
	// Remote multicast setup.
	FUOTADeploymentState_REMOTE_MULTICAST_SETUP FUOTADeploymentState = 1
	// Fragmentation-session setup.
	FUOTADeploymentState_FRAGMENTATION_SESSION_SETUP FUOTADeploymentState = 2
	// Multicast Class-C session setup.
	FUOTADeploymentState_MULTICAST_C_SESSION_SETUP FUOTADeploymentState = 3
	// Enqueue the fragments into the multicast-group queue.
	FUOTADeploymentState_ENQUEUE FUOTADeploymentState = 4
	// Request fragmentation status from devices.
	FUOTADeploymentState_STATUS_REQUEST FUOTADeploymentState = 5
	// Set the per-device status (and errors).
	FUOTADeploymentState_SET_DEVICE_STATUS FUOTADeploymentState = 6
	// Cleanup multicast-group.
	FUOTADeploymentState_CLEANUP FUOTADeploymentState = 7
	// FUOTA deployment has been completed.
	FUOTADeploymentState_DONE FUOTADeploymentState = 8
)

var FUOTADeploymentState_name = map[int32]string{
	0: "MULTICAST_CREATE",
	1: "REMOTE_MULTICAST_SETUP",
	2: "FRAGMENTATION_SESSION_SETUP",
	3: "MULTICAST_C_SESSION_SETUP",
	4: "ENQUEUE",
	5: "STATUS_REQUEST",
	6: "SET_DEVICE_STATUS",
	7: "CLEANUP",
	8: "DONE",
}
var FUOTADeploymentState_value = map[string]int32{
	"MULTICAST_CREATE":            0,
	"REMOTE_MULTICAST_SETUP":      1,
	"FRAGMENTATION_SESSION_SETUP": 2,
	"MULTICAST_C_SESSION_SETUP":   3,
	"ENQUEUE":                     4,
	"STATUS_REQUEST":              5,
	"SET_DEVICE_STATUS":           6,
	"CLEANUP":                     7,
	"DONE":                        8,
}

func (x FUOTADeploymentState) String() string {
	return proto.EnumName(FUOTADeploymentState_name, int32(x))
}
func (FUOTADeploymentState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fuotaDeployment_fd094257035247d9, []int{0}
}

type FUOTADeploymentDeviceState int32

const (
	// Pending.
	FUOTADeploymentDeviceState_PENDING FUOTADeploymentDeviceState = 0
	// Success.
	FUOTADeploymentDeviceState_SUCCESS FUOTADeploymentDeviceState = 1
	// Error.
	FUOTADeploymentDeviceState_ERROR FUOTADeploymentDeviceState = 2
)

var FUOTADeploymentDeviceState_name = map[int32]string{
	0: "PENDING",
	1: "SUCCESS",
	2: "ERROR",
}
var FUOTADeploymentDeviceState_value = map[string]int32{
	"PENDING": 0,
	"SUCCESS": 1,
	"ERROR":   2,
}

func (x FUOTADeploymentDeviceState) String() string {
	return proto.EnumName(FUOTADeploymentDeviceState_name, int32(x))
}
func (FUOTADeploymentDeviceState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fuotaDeployment_fd094257035247d9, []int{1}
}

type FUOTADeployment struct {
	// ID of the deployment (string formatted UUID).
	// This value will be automatically assigned on create.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the deployment.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Multicast type.
	// Currently only Class-C is supported!
	GroupType MulticastGroupType `protobuf:"varint,3,opt,name=group_type,json=groupType,proto3,enum=api.MulticastGroupType" json:"group_type,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,4,opt,name=dr,proto3" json:"dr,omitempty"`
	// Frequency (Hz).
	Frequency uint32 `protobuf:"varint,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Payload.
	Payload []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// Redundancy (number of packages).
	Redundancy float32 `protobuf:"fixed32,7,opt,name=redundancy,proto3" json:"redundancy,omitempty"`
	// Multicast time-out.
	// Please refer to the Remote Multicast Setup specification as this field
	// has a different meaning for Class-B and Class-C groups.
	MulticastTimeout uint32 `protobuf:"varint,8,opt,name=multicast_timeout,json=multicastTimeout,proto3" json:"multicast_timeout,omitempty"`
	// Unicast time-out.
	// Set this to the value in which you at least expect an uplink frame from the
	// device. The FUOTA deployment engine will wait at least for the given time
	// before proceeding with the next steps.
	UnicastTimeout *duration.Duration `protobuf:"bytes,9,opt,name=unicast_timeout,json=unicastTimeout,proto3" json:"unicast_timeout,omitempty"`
	// Deployment state.
	// This value will be automatically set on create.
	State FUOTADeploymentState `protobuf:"varint,10,opt,name=state,proto3,enum=api.FUOTADeploymentState" json:"state,omitempty"`
	// Next step after.
	// This value will be automatically set on create.
	NextStepAfter        *timestamp.Timestamp `protobuf:"bytes,11,opt,name=next_step_after,json=nextStepAfter,proto3" json:"next_step_after,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FUOTADeployment) Reset()         { *m = FUOTADeployment{} }
func (m *FUOTADeployment) String() string { return proto.CompactTextString(m) }
func (*FUOTADeployment) ProtoMessage()    {}
func (*FUOTADeployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_fuotaDeployment_fd094257035247d9, []int{0}
}
func (m *FUOTADeployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FUOTADeployment.Unmarshal(m, b)
}
func (m *FUOTADeployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FUOTADeployment.Marshal(b, m, deterministic)
}
func (dst *FUOTADeployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FUOTADeployment.Merge(dst, src)
}
func (m *FUOTADeployment) XXX_Size() int {
	return xxx_messageInfo_FUOTADeployment.Size(m)
}
func (m *FUOTADeployment) XXX_DiscardUnknown() {
	xxx_messageInfo_FUOTADeployment.DiscardUnknown(m)
}

var xxx_messageInfo_FUOTADeployment proto.InternalMessageInfo

func (m *FUOTADeployment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FUOTADeployment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FUOTADeployment) GetGroupType() MulticastGroupType {
	if m != nil {
		return m.GroupType
	}
	return MulticastGroupType_CLASS_C
}

func (m *FUOTADeployment) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *FUOTADeployment) GetFrequency() uint32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *FUOTADeployment) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FUOTADeployment) GetRedundancy() float32 {
	if m != nil {
		return m.Redundancy
	}
	return 0
}

func (m *FUOTADeployment) GetMulticastTimeout() uint32 {
	if m != nil {
		return m.MulticastTimeout
	}
	return 0
}

func (m *FUOTADeployment) GetUnicastTimeout() *duration.Duration {
	if m != nil {
		return m.UnicastTimeout
	}
	return nil
}

func (m *FUOTADeployment) GetState() FUOTADeploymentState {
	if m != nil {
		return m.State
	}
	return FUOTADeploymentState_MULTICAST_CREATE
}

func (m *FUOTADeployment) GetNextStepAfter() *timestamp.Timestamp {
	if m != nil {
		return m.NextStepAfter
	}
	return nil
}

type CreateFUOTADeploymentForDevEUIRequest struct {
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,1,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// FUOTA deployment.
	FuotaDeployment      *FUOTADeployment `protobuf:"bytes,2,opt,name=fuota_deployment,json=fuotaDeployment,proto3" json:"fuota_deployment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateFUOTADeploymentForDevEUIRequest) Reset()         { *m = CreateFUOTADeploymentForDevEUIRequest{} }
func (m *CreateFUOTADeploymentForDevEUIRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFUOTADeploymentForDevEUIRequest) ProtoMessage()    {}
func (*CreateFUOTADeploymentForDevEUIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fuotaDeployment_fd094257035247d9, []int{1}
}
func (m *CreateFUOTADeploymentForDevEUIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFUOTADeploymentForDevEUIRequest.Unmarshal(m, b)
}
func (m *CreateFUOTADeploymentForDevEUIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFUOTADeploymentForDevEUIRequest.Marshal(b, m, deterministic)
}
func (dst *CreateFUOTADeploymentForDevEUIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFUOTADeploymentForDevEUIRequest.Merge(dst, src)
}
func (m *CreateFUOTADeploymentForDevEUIRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFUOTADeploymentForDevEUIRequest.Size(m)
}
func (m *CreateFUOTADeploymentForDevEUIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFUOTADeploymentForDevEUIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFUOTADeploymentForDevEUIRequest proto.InternalMessageInfo

func (m *CreateFUOTADeploymentForDevEUIRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *CreateFUOTADeploymentForDevEUIRequest) GetFuotaDeployment() *FUOTADeployment {
	if m != nil {
		return m.FuotaDeployment
	}
	return nil
}

type CreateFUOTADeploymentForDevEUIResponse struct {
	// ID of the created deployment (string formatted UUID).
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFUOTADeploymentForDevEUIResponse) Reset() {
	*m = CreateFUOTADeploymentForDevEUIResponse{}
}
func (m *CreateFUOTADeploymentForDevEUIResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFUOTADeploymentForDevEUIResponse) ProtoMessage()    {}
func (*CreateFUOTADeploymentForDevEUIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fuotaDeployment_fd094257035247d9, []int{2}
}
func (m *CreateFUOTADeploymentForDevEUIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFUOTADeploymentForDevEUIResponse.Unmarshal(m, b)
}
func (m *CreateFUOTADeploymentForDevEUIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFUOTADeploymentForDevEUIResponse.Marshal(b, m, deterministic)
}
func (dst *CreateFUOTADeploymentForDevEUIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFUOTADeploymentForDevEUIResponse.Merge(dst, src)
}
func (m *CreateFUOTADeploymentForDevEUIResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFUOTADeploymentForDevEUIResponse.Size(m)
}
func (m *CreateFUOTADeploymentForDevEUIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFUOTADeploymentForDevEUIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFUOTADeploymentForDevEUIResponse proto.InternalMessageInfo

func (m *CreateFUOTADeploymentForDevEUIResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFUOTADeploymentRequest struct {
	// ID of the deployment (string formatted UUID).
	// This value will be automatically assigned on create.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFUOTADeploymentRequest) Reset()         { *m = GetFUOTADeploymentRequest{} }
func (m *GetFUOTADeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*GetFUOTADeploymentRequest) ProtoMessage()    {}
func (*GetFUOTADeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fuotaDeployment_fd094257035247d9, []int{3}
}
func (m *GetFUOTADeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFUOTADeploymentRequest.Unmarshal(m, b)
}
func (m *GetFUOTADeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFUOTADeploymentRequest.Marshal(b, m, deterministic)
}
func (dst *GetFUOTADeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFUOTADeploymentRequest.Merge(dst, src)
}
func (m *GetFUOTADeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_GetFUOTADeploymentRequest.Size(m)
}
func (m *GetFUOTADeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFUOTADeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFUOTADeploymentRequest proto.InternalMessageInfo

func (m *GetFUOTADeploymentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFUOTADeploymentResponse struct {
	FuotaDeployment *FUOTADeployment `protobuf:"bytes,1,opt,name=fuota_deployment,json=fuotaDeployment,proto3" json:"fuota_deployment,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetFUOTADeploymentResponse) Reset()         { *m = GetFUOTADeploymentResponse{} }
func (m *GetFUOTADeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*GetFUOTADeploymentResponse) ProtoMessage()    {}
func (*GetFUOTADeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fuotaDeployment_fd094257035247d9, []int{4}
}
func (m *GetFUOTADeploymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFUOTADeploymentResponse.Unmarshal(m, b)
}
func (m *GetFUOTADeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFUOTADeploymentResponse.Marshal(b, m, deterministic)
}
func (dst *GetFUOTADeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFUOTADeploymentResponse.Merge(dst, src)
}
func (m *GetFUOTADeploymentResponse) XXX_Size() int {
	return xxx_messageInfo_GetFUOTADeploymentResponse.Size(m)
}
func (m *GetFUOTADeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFUOTADeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFUOTADeploymentResponse proto.InternalMessageInfo

func (m *GetFUOTADeploymentResponse) GetFuotaDeployment() *FUOTADeployment {
	if m != nil {
		return m.FuotaDeployment
	}
	return nil
}

func (m *GetFUOTADeploymentResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GetFUOTADeploymentResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ListFUOTADeploymentDevicesRequest struct {
	// ID of the deployment (string formatted UUID).
	// This value will be automatically assigned on create.
	FuotaDeploymentId string `protobuf:"bytes,1,opt,name=fuota_deployment_id,json=fuotaDeploymentID,proto3" json:"fuota_deployment_id,omitempty"`
	// Max number of items to return.
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFUOTADeploymentDevicesRequest) Reset()         { *m = ListFUOTADeploymentDevicesRequest{} }
func (m *ListFUOTADeploymentDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListFUOTADeploymentDevicesRequest) ProtoMessage()    {}
func (*ListFUOTADeploymentDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fuotaDeployment_fd094257035247d9, []int{5}
}
func (m *ListFUOTADeploymentDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFUOTADeploymentDevicesRequest.Unmarshal(m, b)
}
func (m *ListFUOTADeploymentDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFUOTADeploymentDevicesRequest.Marshal(b, m, deterministic)
}
func (dst *ListFUOTADeploymentDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFUOTADeploymentDevicesRequest.Merge(dst, src)
}
func (m *ListFUOTADeploymentDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListFUOTADeploymentDevicesRequest.Size(m)
}
func (m *ListFUOTADeploymentDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFUOTADeploymentDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFUOTADeploymentDevicesRequest proto.InternalMessageInfo

func (m *ListFUOTADeploymentDevicesRequest) GetFuotaDeploymentId() string {
	if m != nil {
		return m.FuotaDeploymentId
	}
	return ""
}

func (m *ListFUOTADeploymentDevicesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListFUOTADeploymentDevicesRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListFUOTADeploymentDevicesResponse struct {
	// Total number of devices for the FUOTA deployment.
	TotalCount           int64                            `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Result               []*FUOTADeploymentDeviceListItem `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ListFUOTADeploymentDevicesResponse) Reset()         { *m = ListFUOTADeploymentDevicesResponse{} }
func (m *ListFUOTADeploymentDevicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListFUOTADeploymentDevicesResponse) ProtoMessage()    {}
func (*ListFUOTADeploymentDevicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fuotaDeployment_fd094257035247d9, []int{6}
}
func (m *ListFUOTADeploymentDevicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFUOTADeploymentDevicesResponse.Unmarshal(m, b)
}
func (m *ListFUOTADeploymentDevicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFUOTADeploymentDevicesResponse.Marshal(b, m, deterministic)
}
func (dst *ListFUOTADeploymentDevicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFUOTADeploymentDevicesResponse.Merge(dst, src)
}
func (m *ListFUOTADeploymentDevicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListFUOTADeploymentDevicesResponse.Size(m)
}
func (m *ListFUOTADeploymentDevicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFUOTADeploymentDevicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFUOTADeploymentDevicesResponse proto.InternalMessageInfo

func (m *ListFUOTADeploymentDevicesResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListFUOTADeploymentDevicesResponse) GetResult() []*FUOTADeploymentDeviceListItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type FUOTADeploymentDeviceListItem struct {
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,1,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device state.
	State FUOTADeploymentDeviceState `protobuf:"varint,3,opt,name=state,proto3,enum=api.FUOTADeploymentDeviceState" json:"state,omitempty"`
	// Error message (in case of error state).
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated at timestamp.
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FUOTADeploymentDeviceListItem) Reset()         { *m = FUOTADeploymentDeviceListItem{} }
func (m *FUOTADeploymentDeviceListItem) String() string { return proto.CompactTextString(m) }
func (*FUOTADeploymentDeviceListItem) ProtoMessage()    {}
func (*FUOTADeploymentDeviceListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_fuotaDeployment_fd094257035247d9, []int{7}
}
func (m *FUOTADeploymentDeviceListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FUOTADeploymentDeviceListItem.Unmarshal(m, b)
}
func (m *FUOTADeploymentDeviceListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FUOTADeploymentDeviceListItem.Marshal(b, m, deterministic)
}
func (dst *FUOTADeploymentDeviceListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FUOTADeploymentDeviceListItem.Merge(dst, src)
}
func (m *FUOTADeploymentDeviceListItem) XXX_Size() int {
	return xxx_messageInfo_FUOTADeploymentDeviceListItem.Size(m)
}
func (m *FUOTADeploymentDeviceListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FUOTADeploymentDeviceListItem.DiscardUnknown(m)
}

var xxx_messageInfo_FUOTADeploymentDeviceListItem proto.InternalMessageInfo

func (m *FUOTADeploymentDeviceListItem) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *FUOTADeploymentDeviceListItem) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *FUOTADeploymentDeviceListItem) GetState() FUOTADeploymentDeviceState {
	if m != nil {
		return m.State
	}
	return FUOTADeploymentDeviceState_PENDING
}

func (m *FUOTADeploymentDeviceListItem) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *FUOTADeploymentDeviceListItem) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *FUOTADeploymentDeviceListItem) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*FUOTADeployment)(nil), "api.FUOTADeployment")
	proto.RegisterType((*CreateFUOTADeploymentForDevEUIRequest)(nil), "api.CreateFUOTADeploymentForDevEUIRequest")
	proto.RegisterType((*CreateFUOTADeploymentForDevEUIResponse)(nil), "api.CreateFUOTADeploymentForDevEUIResponse")
	proto.RegisterType((*GetFUOTADeploymentRequest)(nil), "api.GetFUOTADeploymentRequest")
	proto.RegisterType((*GetFUOTADeploymentResponse)(nil), "api.GetFUOTADeploymentResponse")
	proto.RegisterType((*ListFUOTADeploymentDevicesRequest)(nil), "api.ListFUOTADeploymentDevicesRequest")
	proto.RegisterType((*ListFUOTADeploymentDevicesResponse)(nil), "api.ListFUOTADeploymentDevicesResponse")
	proto.RegisterType((*FUOTADeploymentDeviceListItem)(nil), "api.FUOTADeploymentDeviceListItem")
	proto.RegisterEnum("api.FUOTADeploymentState", FUOTADeploymentState_name, FUOTADeploymentState_value)
	proto.RegisterEnum("api.FUOTADeploymentDeviceState", FUOTADeploymentDeviceState_name, FUOTADeploymentDeviceState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FUOTADeploymentServiceClient is the client API for FUOTADeploymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FUOTADeploymentServiceClient interface {
	// CreateForDevEUI creates a deployment for the given DevEUI.
	CreateForDevEUI(ctx context.Context, in *CreateFUOTADeploymentForDevEUIRequest, opts ...grpc.CallOption) (*CreateFUOTADeploymentForDevEUIResponse, error)
	// Get returns the fuota deployment for the given id.
	Get(ctx context.Context, in *GetFUOTADeploymentRequest, opts ...grpc.CallOption) (*GetFUOTADeploymentResponse, error)
	// ListDevices lists the devices (and status) for the given fuota deployment ID.
	ListDevices(ctx context.Context, in *ListFUOTADeploymentDevicesRequest, opts ...grpc.CallOption) (*ListFUOTADeploymentDevicesResponse, error)
}

type fUOTADeploymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewFUOTADeploymentServiceClient(cc *grpc.ClientConn) FUOTADeploymentServiceClient {
	return &fUOTADeploymentServiceClient{cc}
}

func (c *fUOTADeploymentServiceClient) CreateForDevEUI(ctx context.Context, in *CreateFUOTADeploymentForDevEUIRequest, opts ...grpc.CallOption) (*CreateFUOTADeploymentForDevEUIResponse, error) {
	out := new(CreateFUOTADeploymentForDevEUIResponse)
	err := c.cc.Invoke(ctx, "/api.FUOTADeploymentService/CreateForDevEUI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTADeploymentServiceClient) Get(ctx context.Context, in *GetFUOTADeploymentRequest, opts ...grpc.CallOption) (*GetFUOTADeploymentResponse, error) {
	out := new(GetFUOTADeploymentResponse)
	err := c.cc.Invoke(ctx, "/api.FUOTADeploymentService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTADeploymentServiceClient) ListDevices(ctx context.Context, in *ListFUOTADeploymentDevicesRequest, opts ...grpc.CallOption) (*ListFUOTADeploymentDevicesResponse, error) {
	out := new(ListFUOTADeploymentDevicesResponse)
	err := c.cc.Invoke(ctx, "/api.FUOTADeploymentService/ListDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FUOTADeploymentServiceServer is the server API for FUOTADeploymentService service.
type FUOTADeploymentServiceServer interface {
	// CreateForDevEUI creates a deployment for the given DevEUI.
	CreateForDevEUI(context.Context, *CreateFUOTADeploymentForDevEUIRequest) (*CreateFUOTADeploymentForDevEUIResponse, error)
	// Get returns the fuota deployment for the given id.
	Get(context.Context, *GetFUOTADeploymentRequest) (*GetFUOTADeploymentResponse, error)
	// ListDevices lists the devices (and status) for the given fuota deployment ID.
	ListDevices(context.Context, *ListFUOTADeploymentDevicesRequest) (*ListFUOTADeploymentDevicesResponse, error)
}

func RegisterFUOTADeploymentServiceServer(s *grpc.Server, srv FUOTADeploymentServiceServer) {
	s.RegisterService(&_FUOTADeploymentService_serviceDesc, srv)
}

func _FUOTADeploymentService_CreateForDevEUI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFUOTADeploymentForDevEUIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).CreateForDevEUI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FUOTADeploymentService/CreateForDevEUI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).CreateForDevEUI(ctx, req.(*CreateFUOTADeploymentForDevEUIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTADeploymentService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFUOTADeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FUOTADeploymentService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).Get(ctx, req.(*GetFUOTADeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTADeploymentService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFUOTADeploymentDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTADeploymentServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FUOTADeploymentService/ListDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTADeploymentServiceServer).ListDevices(ctx, req.(*ListFUOTADeploymentDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FUOTADeploymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.FUOTADeploymentService",
	HandlerType: (*FUOTADeploymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateForDevEUI",
			Handler:    _FUOTADeploymentService_CreateForDevEUI_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _FUOTADeploymentService_Get_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _FUOTADeploymentService_ListDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fuotaDeployment.proto",
}

func init() {
	proto.RegisterFile("fuotaDeployment.proto", fileDescriptor_fuotaDeployment_fd094257035247d9)
}

var fileDescriptor_fuotaDeployment_fd094257035247d9 = []byte{
	// 986 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x5e, 0xc7, 0x4d, 0xba, 0x39, 0xd9, 0xb6, 0xee, 0xd0, 0xed, 0xa6, 0xa6, 0xdb, 0x04, 0x23,
	0x76, 0xa3, 0x16, 0x12, 0x29, 0xab, 0x45, 0xb0, 0x5c, 0x20, 0x93, 0x4c, 0xab, 0x48, 0x6d, 0xda,
	0x1d, 0xdb, 0xdc, 0x5a, 0xde, 0x7a, 0x52, 0x19, 0x25, 0xb6, 0xb1, 0xc7, 0x15, 0xd5, 0xaa, 0x17,
	0xf0, 0x0a, 0x5c, 0x22, 0xf1, 0x02, 0x3c, 0x02, 0x97, 0x3c, 0xc2, 0x5e, 0xf0, 0x02, 0x3c, 0x08,
	0x9a, 0xf1, 0xb8, 0x3f, 0x26, 0x69, 0x77, 0xb9, 0x8a, 0xe7, 0x9c, 0xef, 0xfc, 0x7d, 0xe7, 0x27,
	0xf0, 0x78, 0x92, 0x45, 0xcc, 0x1b, 0xd2, 0x78, 0x1a, 0x5d, 0xcc, 0x68, 0xc8, 0xba, 0x71, 0x12,
	0xb1, 0x08, 0xa9, 0x5e, 0x1c, 0xe8, 0xdb, 0x67, 0x51, 0x74, 0x36, 0xa5, 0x3d, 0x2f, 0x0e, 0x7a,
	0x5e, 0x18, 0x46, 0xcc, 0x63, 0x41, 0x14, 0xa6, 0x39, 0x44, 0x6f, 0x49, 0xad, 0x78, 0xbd, 0xc9,
	0x26, 0x3d, 0x16, 0xcc, 0x68, 0xca, 0xbc, 0x59, 0x2c, 0x01, 0x3b, 0x65, 0x80, 0x9f, 0x25, 0xc2,
	0x83, 0xd4, 0x6f, 0xcc, 0xb2, 0x29, 0x0b, 0x4e, 0xbd, 0x94, 0x1d, 0x24, 0x51, 0x26, 0xad, 0x8c,
	0x3f, 0x55, 0x58, 0xdb, 0x77, 0x8e, 0x6d, 0xf3, 0x3a, 0x27, 0xb4, 0x0a, 0x95, 0xc0, 0x6f, 0x2a,
	0x6d, 0xa5, 0x53, 0x27, 0x95, 0xc0, 0x47, 0x08, 0x96, 0x42, 0x6f, 0x46, 0x9b, 0x15, 0x21, 0x11,
	0xdf, 0xe8, 0x4b, 0x80, 0x33, 0xee, 0xc6, 0x65, 0x17, 0x31, 0x6d, 0xaa, 0x6d, 0xa5, 0xb3, 0xda,
	0x7f, 0xd2, 0xf5, 0xe2, 0xa0, 0x7b, 0x74, 0x2b, 0x8c, 0x7d, 0x11, 0x53, 0x52, 0x3f, 0x2b, 0x3e,
	0xb9, 0x6f, 0x3f, 0x69, 0x2e, 0xb5, 0x95, 0xce, 0x0a, 0xa9, 0xf8, 0x09, 0xda, 0x86, 0xfa, 0x24,
	0xa1, 0x3f, 0x66, 0x34, 0x3c, 0xbd, 0x68, 0x56, 0x85, 0xf8, 0x5a, 0x80, 0x9a, 0xb0, 0x1c, 0x7b,
	0x17, 0xd3, 0xc8, 0xf3, 0x9b, 0xb5, 0xb6, 0xd2, 0x79, 0x44, 0x8a, 0x27, 0xda, 0x01, 0x48, 0xa8,
	0x9f, 0x85, 0xbe, 0xc7, 0x0d, 0x97, 0xdb, 0x4a, 0xa7, 0x42, 0x6e, 0x48, 0xd0, 0x1e, 0xac, 0x5f,
	0xd5, 0xeb, 0x72, 0xaa, 0xa2, 0x8c, 0x35, 0x1f, 0x0a, 0xff, 0xda, 0x95, 0xc2, 0xce, 0xe5, 0xe8,
	0x3b, 0x58, 0xcb, 0xc2, 0xdb, 0xd0, 0x7a, 0x5b, 0xe9, 0x34, 0xfa, 0x5b, 0xdd, 0x9c, 0xd4, 0x6e,
	0x41, 0x6a, 0x77, 0x28, 0x49, 0x25, 0xab, 0xd2, 0xa2, 0xf0, 0xd1, 0x83, 0x6a, 0xca, 0x3c, 0x46,
	0x9b, 0x20, 0xb8, 0xd8, 0x12, 0x5c, 0x94, 0x98, 0xb5, 0x38, 0x80, 0xe4, 0x38, 0x1e, 0x34, 0xa4,
	0x3f, 0x31, 0x37, 0x65, 0x34, 0x76, 0xbd, 0x09, 0xa3, 0x49, 0xb3, 0x21, 0x82, 0xea, 0xff, 0x09,
	0x6a, 0x17, 0xad, 0x26, 0x2b, 0xdc, 0xc4, 0x62, 0x34, 0x36, 0xb9, 0x81, 0xf1, 0xb3, 0x02, 0x9f,
	0x0d, 0x12, 0xea, 0x31, 0x5a, 0x8a, 0xb4, 0x1f, 0x25, 0x43, 0x7a, 0x8e, 0x9d, 0x11, 0xe1, 0x54,
	0xa6, 0x0c, 0x3d, 0x81, 0x65, 0x9f, 0x9e, 0xbb, 0x34, 0x0b, 0x64, 0x63, 0x6b, 0xbe, 0xd0, 0xa3,
	0x6f, 0x41, 0x13, 0x33, 0xe9, 0xfa, 0x57, 0xc6, 0xa2, 0xd1, 0x8d, 0xfe, 0xc6, 0xbc, 0x12, 0xc8,
	0x5a, 0x69, 0x82, 0x8d, 0xaf, 0xe0, 0xd9, 0x7d, 0x29, 0xa4, 0x71, 0x14, 0xa6, 0xb4, 0x3c, 0x57,
	0xc6, 0x1e, 0x6c, 0x1d, 0x50, 0x56, 0x0e, 0x20, 0x13, 0x2e, 0x83, 0xdf, 0x29, 0xa0, 0xcf, 0x43,
	0x4b, 0xdf, 0xf3, 0xca, 0x50, 0x3e, 0xa0, 0x0c, 0xf4, 0x35, 0xc0, 0xa9, 0x28, 0xc3, 0x77, 0xbd,
	0x82, 0x81, 0xbb, 0x3a, 0x51, 0x97, 0x68, 0x53, 0x98, 0x66, 0xb1, 0x5f, 0x98, 0xaa, 0xf7, 0x9b,
	0x4a, 0xb4, 0xc9, 0x78, 0x03, 0x3f, 0x39, 0x0c, 0xd2, 0x72, 0x59, 0x43, 0x7a, 0x1e, 0x9c, 0xd2,
	0xb4, 0xe0, 0xa2, 0x0b, 0x1f, 0x95, 0x8b, 0x73, 0xaf, 0xc8, 0x59, 0x2f, 0x55, 0x32, 0x1a, 0xa2,
	0x0d, 0xa8, 0x4e, 0x83, 0x59, 0x90, 0x97, 0xa1, 0x92, 0xfc, 0x81, 0x36, 0xa1, 0x16, 0x4d, 0x26,
	0x29, 0xcd, 0x53, 0x54, 0x89, 0x7c, 0xf1, 0x1c, 0x8c, 0xbb, 0x72, 0x90, 0x0c, 0xb7, 0xa0, 0xc1,
	0x22, 0xe6, 0x4d, 0xdd, 0xd3, 0x28, 0x93, 0xe4, 0xaa, 0x04, 0x84, 0x68, 0xc0, 0x25, 0xe8, 0x15,
	0xd4, 0x12, 0x9a, 0x66, 0x53, 0x1e, 0x56, 0xed, 0x34, 0xfa, 0xc6, 0x3c, 0xe2, 0x73, 0xaf, 0x3c,
	0xdc, 0x88, 0xd1, 0x19, 0x91, 0x16, 0xc6, 0x1f, 0x15, 0x78, 0x7a, 0x27, 0x72, 0xf1, 0x00, 0xb7,
	0xa0, 0xe1, 0x0b, 0xa8, 0x7b, 0xe3, 0x48, 0x41, 0x2e, 0x1a, 0xf3, 0x53, 0xf5, 0xb2, 0xd8, 0xcc,
	0xfc, 0x4a, 0xb5, 0x16, 0xa7, 0x75, 0x6b, 0x3f, 0x3f, 0x85, 0x15, 0x9a, 0x24, 0x51, 0xe2, 0xce,
	0x68, 0x9a, 0x7a, 0x67, 0x54, 0x1c, 0xad, 0x3a, 0x79, 0x24, 0x84, 0x47, 0xb9, 0xac, 0x34, 0x35,
	0xd5, 0xff, 0x3f, 0x35, 0xb5, 0x0f, 0x98, 0x9a, 0xdd, 0xbf, 0x15, 0xd8, 0x98, 0x77, 0x5a, 0xd0,
	0x06, 0x68, 0x47, 0xce, 0xa1, 0x3d, 0x1a, 0x98, 0x96, 0xed, 0x0e, 0x08, 0x36, 0x6d, 0xac, 0x3d,
	0x40, 0x3a, 0x6c, 0x12, 0x7c, 0x74, 0x6c, 0x63, 0xf7, 0x5a, 0x69, 0x61, 0xdb, 0x39, 0xd1, 0x14,
	0xd4, 0x82, 0x8f, 0xf7, 0x89, 0x79, 0x70, 0x84, 0xc7, 0xb6, 0x69, 0x8f, 0x8e, 0xc7, 0xae, 0x85,
	0x2d, 0x2b, 0xff, 0xe5, 0x80, 0x0a, 0x7a, 0x0a, 0x5b, 0x37, 0x5c, 0x96, 0xd4, 0x2a, 0x6a, 0xc0,
	0x32, 0x1e, 0xbf, 0x76, 0xb0, 0x83, 0xb5, 0x25, 0x84, 0x60, 0xd5, 0xb2, 0x4d, 0xdb, 0xb1, 0x5c,
	0x82, 0x5f, 0x3b, 0xd8, 0xb2, 0xb5, 0x2a, 0x7a, 0x0c, 0xeb, 0x16, 0xb6, 0xdd, 0x21, 0xfe, 0x7e,
	0x34, 0xc0, 0x6e, 0xae, 0xd6, 0x6a, 0xdc, 0x6e, 0x70, 0x88, 0xcd, 0xb1, 0x73, 0xa2, 0x2d, 0xa3,
	0x87, 0xb0, 0x34, 0x3c, 0x1e, 0x63, 0xed, 0xe1, 0xae, 0x09, 0xfa, 0xe2, 0xce, 0x70, 0xa3, 0x13,
	0x3c, 0x1e, 0x8e, 0xc6, 0x07, 0xda, 0x03, 0xfe, 0xb0, 0x9c, 0xc1, 0x00, 0x5b, 0x96, 0xa6, 0xa0,
	0x3a, 0x54, 0x31, 0x21, 0xc7, 0x44, 0xab, 0xf4, 0xff, 0x52, 0x61, 0xb3, 0x4c, 0x0e, 0x4d, 0xb8,
	0x13, 0xf4, 0xbb, 0x02, 0x6b, 0xf2, 0x56, 0x15, 0xc7, 0x09, 0xed, 0x8a, 0x71, 0x78, 0xaf, 0x23,
	0xaa, 0xef, 0xbd, 0x17, 0x36, 0xdf, 0x17, 0xa3, 0xff, 0xcb, 0xbb, 0x7f, 0x7e, 0xad, 0x7c, 0x6e,
	0x3c, 0x17, 0x7f, 0xe8, 0xf9, 0x3c, 0xa6, 0xbd, 0xb7, 0x72, 0x88, 0x2f, 0x7b, 0x62, 0x6d, 0xbf,
	0xb8, 0xde, 0xe8, 0x57, 0xca, 0x2e, 0xfa, 0x01, 0xd4, 0x03, 0xca, 0xd0, 0x8e, 0x88, 0xb3, 0xf0,
	0x36, 0xea, 0xad, 0x85, 0x7a, 0x19, 0xdb, 0x10, 0xb1, 0xb7, 0x91, 0x2e, 0x62, 0x97, 0x23, 0xf5,
	0xde, 0x06, 0xfe, 0x25, 0xfa, 0x4d, 0x81, 0x06, 0xdf, 0x2e, 0xb9, 0xe7, 0xe8, 0x99, 0x70, 0x7a,
	0xef, 0x31, 0xd2, 0x9f, 0xdf, 0x8b, 0x93, 0x49, 0x7c, 0x23, 0x92, 0x78, 0x89, 0x5e, 0x2c, 0x48,
	0x62, 0xce, 0x49, 0xbb, 0x2c, 0x78, 0x7a, 0x53, 0x13, 0x1b, 0xf0, 0xe2, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x7c, 0x7d, 0x7a, 0x32, 0x31, 0x09, 0x00, 0x00,
}
